version: "3.9"

services:
  frontend:
    build:
      context: ./frontend   # your react project folder
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_W_API_KEY=${VITE_W_API_KEY}
      - VITE_P_API_KEY=${VITE_P_API_KEY}
      - VITE_BACKEND_URL=http://backend:8081
    depends_on:
      - backend

  backend:
    build:
      context: ./backend    # your spring boot folder
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
